### ISSUE TITLE
Add AML restricted genes

### ISSUE THREAD

**Issue by amanda-hi** [FredHutch/target-data-viz#26]
Add additional button to indicate if the searched gene is AML-restricted.

**Comment by Logan-Wallace** [comment]
@jpeplin has added a button to the app to address this. 
<img width="253" alt="Screenshot 2024-08-29 at 9 48 21 AM" src="https://github.com/user-attachments/assets/bdde7a9b-1022-4ecd-8438-9eb8fae57036">
