### ISSUE TITLE
Update box/violin plots to use plotly tooltips

### ISSUE THREAD

**Issue by amanda-hi** [FredHutch/target-data-viz#30]
It would be nice to be able to hover over the outliers of a box or violin plot and see the sample ID associated with that point. 

Possible solution here: 
https://stackoverflow.com/questions/47518245/plotly-annotate-outliers-with-sample-names-in-boxplot

It will require `plotly` to be added as a package when the Docker container is built.

**Comment by Logan-Wallace** [comment]
Started working on this issue. Rendering with plotly allows for a lot of added functionality, including the tooltip on hover feature. However, the geom layers aren't rendering with plotly in the same manner as ggplot2 so I am currently working on a solution for this.
